name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "master", "Module-7" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./weather-report

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: weather-report/package-lock.json
    - run: npm ci
    - name: Install ESLint
      run: npm install eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin --save-dev
    - name: Run ESLint
      run: npx eslint . --ext .ts

  test:
    name: Run Tests
    needs: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./weather-report

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: weather-report/package-lock.json
    - run: npm ci
    - name: Install Jest
      run: npm install --save-dev jest ts-jest @types/jest
    - name: Run tests
      run: npm test

  build:
    name: Build Project
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./weather-report

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: weather-report/package-lock.json
    - run: npm ci
    - name: Build
      run: npm run build

  sonarcloud:
    name: SonarCloud Analysis
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./weather-report

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=BINAR-Learning_demo-repository
          -Dsonar.organization=binar-learning
          -Dsonar.sources=./weather-report/src
          -Dsonar.tests=./weather-report/tests
          -Dsonar.javascript.lcov.reportPaths=./weather-report/coverage/lcov.info
          -Dsonar.qualitygate.wait=true
          -Dsonar.qualitygate.conditions=["coverage>=80","new_bugs=0","new_code_smells=0"]
